#!/usr/bin/env python
"""
Run migration SQL directly via Django ORM
"""
import os
import sys
import django

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from django.db import connection

migration_sql = """
BEGIN;
ALTER TABLE "companies" ALTER COLUMN "brief_description" TYPE varchar(2000);
CREATE TABLE "glossary_terms" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "term" varchar(200) NOT NULL UNIQUE, "definition" text NOT NULL, "category" varchar(20) NOT NULL, "related_links" jsonb NOT NULL, "keywords" varchar(500) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL);
ALTER TABLE "glossary_terms" ADD CONSTRAINT "glossary_terms_created_by_id_de08e3a7_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "glossary_terms_term_fcfebf97_like" ON "glossary_terms" ("term" varchar_pattern_ops);
CREATE INDEX "glossary_terms_created_by_id_de08e3a7" ON "glossary_terms" ("created_by_id");
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('core', '0028_alter_company_brief_description_glossaryterm', NOW());
COMMIT;
"""

try:
    with connection.cursor() as cursor:
        cursor.execute(migration_sql)
    print("Migration applied successfully!")
except Exception as e:
    print(f"Error applying migration: {e}")
    sys.exit(1)
