from django.db import models
from django.utils import timezone


class WeeklyIndustryReport(models.Model):
    """
    Friday afternoon snapshot of mining-industry activity for the trailing
    week (Fri close -> Fri close, EST). One row per week_ending date.
    Generated by `generate_weekly_industry_report_task` after the daily
    stock-price fetch completes at 4:30 PM ET.
    """

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('generating', 'Generating'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]

    # The Friday whose close anchors the report (unique key).
    week_ending = models.DateField(unique=True)

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')

    # Rendered output
    html = models.TextField(blank=True, default='')
    pdf_file = models.FileField(upload_to='reports/weekly/', blank=True, null=True)

    # Raw data behind the report (movers, metals, financings, themes, GA4).
    # Frozen so the report can be re-rendered or audited without re-querying.
    data_snapshot = models.JSONField(default=dict, blank=True)

    # Narrative text generated by the LLM, kept separately for re-use.
    executive_summary = models.TextField(blank=True, default='')

    # Operational
    generated_at = models.DateTimeField(default=timezone.now)
    generation_duration_seconds = models.IntegerField(null=True, blank=True)
    error_message = models.TextField(blank=True, default='')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'weekly_industry_reports'
        ordering = ['-week_ending']
        indexes = [
            models.Index(fields=['-week_ending']),
            models.Index(fields=['status', '-week_ending']),
        ]

    def __str__(self):
        return f"Weekly Industry Report — week ending {self.week_ending} ({self.status})"
