# Generated by Django 5.0.1 on 2025-11-15 16:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("ticker_symbol", models.CharField(blank=True, max_length=10)),
                (
                    "exchange",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tsx", "TSX"),
                            ("tsxv", "TSX Venture"),
                            ("cse", "CSE"),
                            ("otc", "OTC"),
                            ("asx", "ASX"),
                            ("aim", "AIM London"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("public", "Public - Listed"),
                            ("public_cpc", "CPC/SPAC"),
                            ("subsidiary", "Subsidiary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("incorporation_date", models.DateField(blank=True, null=True)),
                ("jurisdiction", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("headquarters_city", models.CharField(blank=True, max_length=100)),
                ("headquarters_country", models.CharField(blank=True, max_length=100)),
                ("ceo_name", models.CharField(blank=True, max_length=200)),
                ("cfo_name", models.CharField(blank=True, max_length=200)),
                ("ir_contact_name", models.CharField(blank=True, max_length=200)),
                ("ir_contact_email", models.EmailField(blank=True, max_length=254)),
                ("ir_contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "market_cap_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("shares_outstanding", models.BigIntegerField(blank=True, null=True)),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "companies",
                "db_table": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("admin", "Platform Admin"),
                            ("company", "Company Representative"),
                            ("investor", "Investor"),
                            ("analyst", "Analyst"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("linkedin_url", models.URLField(blank=True)),
                ("bio", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CommodityPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commodity",
                    models.CharField(
                        choices=[
                            ("gold", "Gold (USD/oz)"),
                            ("silver", "Silver (USD/oz)"),
                            ("copper", "Copper (USD/lb)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "commodity_prices",
                "ordering": ["-date"],
                "unique_together": {("commodity", "date")},
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("price_above", "Price Above"),
                            ("price_below", "Price Below"),
                            ("volume_spike", "Volume Spike"),
                            ("news_release", "News Release"),
                            ("financing", "New Financing"),
                            ("resource_update", "Resource Update"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
            },
        ),
        migrations.CreateModel(
            name="Financing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financing_type",
                    models.CharField(
                        choices=[
                            ("private_placement", "Private Placement"),
                            ("bought_deal", "Bought Deal"),
                            ("rights_offering", "Rights Offering"),
                            ("flow_through", "Flow-Through Shares"),
                            ("warrant_exercise", "Warrant Exercise"),
                            ("debt", "Debt Financing"),
                            ("royalty_stream", "Royalty/Stream"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("announced", "Announced"),
                            ("closing", "Closing"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("announced_date", models.DateField()),
                ("closing_date", models.DateField(blank=True, null=True)),
                (
                    "amount_raised_usd",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "price_per_share",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("shares_issued", models.BigIntegerField(blank=True, null=True)),
                ("has_warrants", models.BooleanField(default=False)),
                (
                    "warrant_strike_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("warrant_expiry_date", models.DateField(blank=True, null=True)),
                ("use_of_proceeds", models.TextField(blank=True)),
                ("lead_agent", models.CharField(blank=True, max_length=200)),
                ("press_release_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financings",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "financings",
                "ordering": ["-announced_date"],
            },
        ),
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "investor_type",
                    models.CharField(
                        choices=[
                            ("individual_retail", "Retail Investor"),
                            ("individual_hnw", "High Net Worth Individual"),
                            ("family_office", "Family Office"),
                            ("fund_pe", "Private Equity Fund"),
                            ("fund_hedge", "Hedge Fund"),
                            ("fund_mutual", "Mutual Fund"),
                            ("institution", "Institution"),
                            ("strategic", "Strategic Investor"),
                            ("insider", "Insider/Management"),
                        ],
                        max_length=30,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("linkedin_url", models.URLField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("focus_regions", models.JSONField(blank=True, default=list)),
                ("focus_commodities", models.JSONField(blank=True, default=list)),
                (
                    "preferred_project_stages",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "typical_check_size_min_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "typical_check_size_max_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "relationship_strength",
                    models.IntegerField(
                        blank=True,
                        help_text="1=Cold, 5=Strong relationship",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "investors",
                "ordering": ["company_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="InvestorCommunication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone Call"),
                            ("meeting", "In-Person Meeting"),
                            ("video_call", "Video Call"),
                            ("conference", "Conference Meeting"),
                            ("site_visit", "Site Visit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("communication_date", models.DateTimeField()),
                ("subject", models.CharField(blank=True, max_length=300)),
                ("notes", models.TextField(blank=True)),
                ("requires_followup", models.BooleanField(default=False)),
                ("followup_date", models.DateField(blank=True, null=True)),
                ("followup_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investor_comms",
                        to="core.company",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="core.investor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Company user who logged this",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "investor_communications",
                "ordering": ["-communication_date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "project_stage",
                    models.CharField(
                        choices=[
                            ("grassroots", "Grassroots Exploration"),
                            ("early_exploration", "Early Stage Exploration"),
                            ("advanced_exploration", "Advanced Exploration"),
                            ("resource", "Resource Stage"),
                            ("pea", "PEA Completed"),
                            ("pfs", "PFS Completed"),
                            ("fs", "Feasibility Study"),
                            ("permitting", "Permitting"),
                            ("development", "Development"),
                            ("production", "Production"),
                            ("care_maintenance", "Care & Maintenance"),
                            ("closed", "Closed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "primary_commodity",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("copper", "Copper"),
                            ("multi_metal", "Multi-Metal"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("province_state", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "ownership_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("acquisition_date", models.DateField(blank=True, null=True)),
                ("last_drill_program", models.DateField(blank=True, null=True)),
                ("is_flagship", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-is_flagship", "name"],
            },
        ),
        migrations.CreateModel(
            name="NewsRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "release_type",
                    models.CharField(
                        choices=[
                            ("drill_results", "Drill Results"),
                            ("financing", "Financing Announcement"),
                            ("resource_update", "Resource Update"),
                            ("study_results", "Study Results"),
                            ("corporate", "Corporate Update"),
                            ("acquisition", "Acquisition/Disposition"),
                            ("management", "Management Change"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("release_date", models.DateField()),
                ("summary", models.TextField(blank=True)),
                ("full_text", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                (
                    "is_material",
                    models.BooleanField(default=False, help_text="Material news event"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_releases",
                        to="core.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "news_releases",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="EconomicStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "study_type",
                    models.CharField(
                        choices=[
                            ("pea", "Preliminary Economic Assessment"),
                            ("pfs", "Pre-Feasibility Study"),
                            ("fs", "Feasibility Study"),
                            ("updated_fs", "Updated Feasibility Study"),
                        ],
                        max_length=20,
                    ),
                ),
                ("release_date", models.DateField()),
                (
                    "npv_5_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="NPV at 5% discount rate (USD millions)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "irr_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "payback_years",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "annual_production_oz",
                    models.IntegerField(
                        blank=True, help_text="Annual gold production (oz)", null=True
                    ),
                ),
                (
                    "mine_life_years",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "aisc_per_oz",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="All-in Sustaining Cost (USD/oz)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "initial_capex_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Initial CAPEX (USD millions)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "gold_price_assumption",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "exchange_rate_assumption",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                ("report_url", models.URLField(blank=True)),
                ("qualified_person", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="economic_studies",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "economic_studies",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ni43101", "NI 43-101 Technical Report"),
                            ("presentation", "Corporate Presentation"),
                            ("financial_stmt", "Financial Statements"),
                            ("mda", "MD&A"),
                            ("annual_report", "Annual Report"),
                            ("factsheet", "Fact Sheet"),
                            ("map", "Project Map"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("document_date", models.DateField()),
                ("file_url", models.URLField()),
                (
                    "file_size_mb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-document_date"],
            },
        ),
        migrations.CreateModel(
            name="ResourceEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("inferred", "Inferred"),
                            ("indicated", "Indicated"),
                            ("measured", "Measured"),
                            ("mni", "Measured & Indicated"),
                            ("proven", "Proven (Reserve)"),
                            ("probable", "Probable (Reserve)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("ni43101", "NI 43-101"),
                            ("jorc", "JORC"),
                            ("samrec", "SAMREC"),
                            ("other", "Other"),
                        ],
                        default="ni43101",
                        max_length=20,
                    ),
                ),
                ("tonnes", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "gold_grade_gpt",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "gold_ounces",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "silver_grade_gpt",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "silver_ounces",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "copper_grade_pct",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("report_date", models.DateField()),
                (
                    "cutoff_grade",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("effective_date", models.DateField()),
                ("qualified_person", models.CharField(blank=True, max_length=200)),
                ("report_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "resource_estimates",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "companies",
                    models.ManyToManyField(
                        related_name="in_watchlists", to="core.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "watchlists",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_end_date", models.DateField()),
                (
                    "cash_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "working_capital_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "burn_rate_monthly_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "runway_months",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("meters_drilled_period", models.IntegerField(blank=True, null=True)),
                (
                    "ev_per_resource_oz",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_metrics",
                "ordering": ["-period_end_date"],
                "unique_together": {("company", "period_end_date")},
            },
        ),
        migrations.CreateModel(
            name="InvestorPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shares_held", models.BigIntegerField()),
                (
                    "percentage_ownership",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("position_date", models.DateField(help_text="Date of last update")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="e.g., SEDI, self-reported",
                        max_length=100,
                    ),
                ),
                ("is_insider", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investor_positions",
                        to="core.company",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="core.investor",
                    ),
                ),
            ],
            options={
                "db_table": "investor_positions",
                "unique_together": {("investor", "company")},
            },
        ),
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("high_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("low_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("close_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("volume", models.BigIntegerField()),
                (
                    "market_cap_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_data",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "market_data",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["company", "-date"],
                        name="market_data_company_59212e_idx",
                    )
                ],
                "unique_together": {("company", "date")},
            },
        ),
    ]
