# Generated by Django 5.0.1 on 2025-11-18 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("section_title", models.CharField(blank=True, max_length=500)),
                ("text", models.TextField()),
                ("token_count", models.IntegerField()),
                (
                    "chroma_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="core.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_chunks",
                "ordering": ["document", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["document", "chunk_index"],
                        name="document_ch_documen_15f3c0_idx",
                    )
                ],
            },
        ),
    ]
