# Generated by Django 5.0.1 on 2025-11-18 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_documentchunk"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ni43101", "NI 43-101 Technical Report"),
                            ("news_release", "News Release"),
                            ("financial_statement", "Financial Statement"),
                            ("presentation", "Presentation"),
                            ("other", "Other"),
                        ],
                        default="ni43101",
                        max_length=30,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank for auto-detection",
                        max_length=200,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank for auto-detection",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress_message",
                    models.TextField(blank=True, help_text="Current processing step"),
                ),
                ("error_message", models.TextField(blank=True)),
                ("resources_created", models.IntegerField(default=0)),
                ("chunks_created", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_time_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_jobs",
                        to="core.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_processing_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="document_pr_status_d0e911_idx",
                    ),
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="document_pr_created_9cae3f_idx",
                    ),
                ],
            },
        ),
    ]
