# Generated by Django 5.0.1 on 2025-11-28 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_documentprocessingjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumDiscussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("message_count", models.IntegerField(default=0)),
                ("participant_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_discussions",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_discussions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forum_discussions",
                "ordering": ["-is_pinned", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_highlighted", models.BooleanField(default=False)),
                ("is_flagged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.forumdiscussion",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="core.forummessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forum_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestSpeakerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live Now"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("is_moderated", models.BooleanField(default=True)),
                ("allow_anonymous_questions", models.BooleanField(default=False)),
                ("max_participants", models.IntegerField(blank=True, null=True)),
                ("total_questions", models.IntegerField(default=0)),
                ("total_participants", models.IntegerField(default=0)),
                ("is_archived", models.BooleanField(default=False)),
                ("archive_url", models.URLField(blank=True)),
                ("transcript_url", models.URLField(blank=True)),
                ("transcript_content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_sessions",
                        to="core.company",
                    ),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_sessions",
                        to="core.forumdiscussion",
                    ),
                ),
            ],
            options={
                "db_table": "guest_speaker_sessions",
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="SessionModerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_approve_questions", models.BooleanField(default=True)),
                ("can_reject_questions", models.BooleanField(default=True)),
                ("can_delete_messages", models.BooleanField(default=True)),
                ("can_control_session", models.BooleanField(default=False)),
                ("questions_approved", models.IntegerField(default=0)),
                ("questions_rejected", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderators",
                        to="core.guestspeakersession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderated_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "session_moderators",
            },
        ),
        migrations.CreateModel(
            name="SessionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("is_currently_active", models.BooleanField(default=True)),
                ("messages_sent", models.IntegerField(default=0)),
                ("questions_asked", models.IntegerField(default=0)),
                ("questions_upvoted", models.IntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="core.guestspeakersession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attended_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "session_participants",
            },
        ),
        migrations.CreateModel(
            name="SessionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("answered", "Answered"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("upvote_count", models.IntegerField(default=0)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answer_to_question",
                        to="core.forummessage",
                    ),
                ),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asked_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_question",
                        to="core.forummessage",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.guestspeakersession",
                    ),
                ),
            ],
            options={
                "db_table": "session_questions",
                "ordering": ["-priority", "-upvote_count", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("session_reminder_24h", "24 Hour Reminder"),
                            ("session_reminder_1h", "1 Hour Reminder"),
                            ("session_starting", "Session Starting"),
                            ("session_live", "Session Live Now"),
                            ("session_ended", "Session Ended"),
                            ("question_approved", "Question Approved"),
                            ("question_answered", "Question Answered"),
                            ("speaker_response", "Speaker Responded"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("action_url", models.URLField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.guestspeakersession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.sessionquestion",
                    ),
                ),
            ],
            options={
                "db_table": "session_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionUpvote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_upvotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upvotes",
                        to="core.sessionquestion",
                    ),
                ),
            ],
            options={
                "db_table": "question_upvotes",
            },
        ),
        migrations.CreateModel(
            name="SessionSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("confirmed", models.BooleanField(default=False)),
                ("questions_answered", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="core.guestspeakersession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "session_speakers",
            },
        ),
        migrations.CreateModel(
            name="UserPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                ("is_typing", models.BooleanField(default=False)),
                ("connection_id", models.CharField(blank=True, max_length=255)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_presences",
                        to="core.forumdiscussion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_presence",
            },
        ),
        migrations.AddIndex(
            model_name="forumdiscussion",
            index=models.Index(
                fields=["company", "is_active", "-updated_at"],
                name="forum_discu_company_b84762_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forumdiscussion",
            index=models.Index(
                fields=["company", "is_archived"], name="forum_discu_company_b431cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumdiscussion",
            index=models.Index(
                fields=["-is_pinned", "-updated_at"],
                name="forum_discu_is_pinn_bc8821_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forummessage",
            index=models.Index(
                fields=["discussion", "created_at"],
                name="forum_messa_discuss_8f79cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forummessage",
            index=models.Index(
                fields=["discussion", "is_pinned", "-created_at"],
                name="forum_messa_discuss_87a547_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forummessage",
            index=models.Index(
                fields=["user", "-created_at"], name="forum_messa_user_id_569873_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forummessage",
            index=models.Index(
                fields=["discussion", "is_deleted", "created_at"],
                name="forum_messa_discuss_39a89f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guestspeakersession",
            index=models.Index(
                fields=["company", "scheduled_start"],
                name="guest_speak_company_9526a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guestspeakersession",
            index=models.Index(
                fields=["status", "scheduled_start"],
                name="guest_speak_status_2ceb76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guestspeakersession",
            index=models.Index(
                fields=["company", "status", "-scheduled_start"],
                name="guest_speak_company_0eb67c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sessionmoderator",
            unique_together={("session", "user")},
        ),
        migrations.AddIndex(
            model_name="sessionparticipant",
            index=models.Index(
                fields=["session", "is_currently_active"],
                name="session_par_session_631d3f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionparticipant",
            index=models.Index(
                fields=["user", "-joined_at"], name="session_par_user_id_998408_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sessionparticipant",
            unique_together={("session", "user")},
        ),
        migrations.AddIndex(
            model_name="sessionquestion",
            index=models.Index(
                fields=["session", "status", "-priority"],
                name="session_que_session_961694_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionquestion",
            index=models.Index(
                fields=["session", "-upvote_count"],
                name="session_que_session_97912e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionquestion",
            index=models.Index(
                fields=["asked_by", "-created_at"],
                name="session_que_asked_b_646f3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionnotification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="session_not_user_id_75a54e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionnotification",
            index=models.Index(
                fields=["session", "notification_type"],
                name="session_not_session_0304d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionnotification",
            index=models.Index(
                fields=["is_sent", "scheduled_for"],
                name="session_not_is_sent_537a8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionupvote",
            index=models.Index(
                fields=["question", "user"], name="question_up_questio_a72f11_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questionupvote",
            unique_together={("question", "user")},
        ),
        migrations.AddIndex(
            model_name="sessionspeaker",
            index=models.Index(
                fields=["session", "is_primary"], name="session_spe_session_4ad886_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sessionspeaker",
            unique_together={("session", "user")},
        ),
        migrations.AddIndex(
            model_name="userpresence",
            index=models.Index(
                fields=["discussion", "is_online"],
                name="user_presen_discuss_f786c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userpresence",
            index=models.Index(
                fields=["user", "discussion"], name="user_presen_user_id_8ac666_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpresence",
            index=models.Index(
                fields=["discussion", "is_typing"],
                name="user_presen_discuss_b156cd_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userpresence",
            unique_together={("user", "discussion")},
        ),
    ]
