# Generated by Django 5.0.1 on 2025-11-29 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_forumdiscussion_forummessage_guestspeakersession_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("topic", models.CharField(max_length=255)),
                ("agenda", models.TextField(blank=True)),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("duration_minutes", models.IntegerField()),
                (
                    "format",
                    models.CharField(
                        choices=[("video", "Video Stream"), ("text", "Text Chat")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("max_participants", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("live", "Live Now"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("is_recorded", models.BooleanField(default=False)),
                ("recording_url", models.URLField(blank=True)),
                ("transcript_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("registered_count", models.IntegerField(default=0)),
                ("attended_count", models.IntegerField(default=0)),
                ("questions_count", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_events",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="EventSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaking_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="core.speakerevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("attended", "Attended"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="core.speakerevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("applause", "Applause"),
                            ("thumbs_up", "Thumbs Up"),
                            ("fire", "Fire"),
                            ("heart", "Heart"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="core.speakerevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("answered", "Answered"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                ("upvotes", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "answered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_event_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.speakerevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-upvotes", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="speakerevent",
            index=models.Index(
                fields=["company", "status"], name="core_speake_company_42e5c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="speakerevent",
            index=models.Index(
                fields=["status", "scheduled_start"],
                name="core_speake_status_3ebe2b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="speakerevent",
            index=models.Index(
                fields=["-scheduled_start"], name="core_speake_schedul_1418a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventspeaker",
            index=models.Index(
                fields=["event", "is_primary"], name="core_events_event_i_85626a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventspeaker",
            unique_together={("event", "user")},
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["event", "status"], name="core_eventr_event_i_a18f22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["user", "-registered_at"], name="core_eventr_user_id_2a4fda_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("event", "user")},
        ),
        migrations.AddIndex(
            model_name="eventreaction",
            index=models.Index(
                fields=["event", "reaction_type"], name="core_eventr_event_i_583125_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventreaction",
            index=models.Index(
                fields=["-timestamp"], name="core_eventr_timesta_3abf06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventquestion",
            index=models.Index(
                fields=["event", "status"], name="core_eventq_event_i_ab9adf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventquestion",
            index=models.Index(
                fields=["-upvotes", "-created_at"],
                name="core_eventq_upvotes_336fc5_idx",
            ),
        ),
    ]
