# Generated by Django 5.0.1 on 2025-11-30 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_speakerevent_eventspeaker_eventregistration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_type",
                    models.CharField(
                        choices=[
                            ("basics", "Mining Financing Basics"),
                            ("regulations", "Canadian Securities Regulations"),
                            ("investor_rights", "Investor Rights & Obligations"),
                            ("risk_disclosure", "Risk Disclosures"),
                            ("subscription_agreement", "Subscription Agreement Guide"),
                            ("drs", "Direct Registration System (DRS)"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("content", models.TextField(help_text="HTML/Markdown content")),
                ("estimated_read_time_minutes", models.IntegerField(default=5)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="Required for accreditation process"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "educational_modules",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="FinancingAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_subscriptions", models.IntegerField(default=0)),
                ("total_subscribers", models.IntegerField(default=0)),
                (
                    "total_committed_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_funded_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_shares_allocated", models.BigIntegerField(default=0)),
                (
                    "status_breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Breakdown by agreement status: {draft: 2, signed: 5, funded: 10}",
                    ),
                ),
                (
                    "investor_type_breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Breakdown by investor type: {individual: 8, institutional: 2}",
                    ),
                ),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "financing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregate_data",
                        to="core.financing",
                    ),
                ),
            ],
            options={
                "db_table": "financing_aggregates",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_shares", models.BigIntegerField()),
                (
                    "price_per_share",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "total_investment_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("includes_warrants", models.BooleanField(default=False)),
                ("warrant_shares", models.BigIntegerField(blank=True, null=True)),
                (
                    "warrant_strike_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("warrant_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_signature", "Pending Signature"),
                            ("signed", "Signed"),
                            ("accepted", "Accepted by Company"),
                            ("funded", "Funded"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("agreement_pdf_url", models.URLField(blank=True)),
                ("docusign_envelope_id", models.CharField(blank=True, max_length=255)),
                ("investor_signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "investor_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("company_accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_instructions_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("payment_received_at", models.DateTimeField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=255)),
                ("shares_issued", models.BooleanField(default=False)),
                ("shares_issued_at", models.DateTimeField(blank=True, null=True)),
                ("drs_statement_sent_at", models.DateTimeField(blank=True, null=True)),
                ("certificate_number", models.CharField(blank=True, max_length=100)),
                ("accreditation_verified", models.BooleanField(default=False)),
                ("kyc_completed", models.BooleanField(default=False)),
                ("aml_check_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_agreements",
                        to="core.company",
                    ),
                ),
                (
                    "company_accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "financing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_agreements",
                        to="core.financing",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscription_agreements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wire", "Wire Transfer"),
                            ("ach", "ACH Transfer"),
                            ("check", "Check"),
                            ("crypto", "Cryptocurrency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("bank_account_name", models.CharField(blank=True, max_length=255)),
                ("bank_account_number", models.CharField(blank=True, max_length=255)),
                ("routing_number", models.CharField(blank=True, max_length=50)),
                ("swift_code", models.CharField(blank=True, max_length=50)),
                (
                    "reference_code",
                    models.CharField(
                        help_text="Unique reference for payment tracking",
                        max_length=100,
                    ),
                ),
                ("special_instructions", models.TextField(blank=True)),
                ("sent_to_investor_at", models.DateTimeField(blank=True, null=True)),
                ("viewed_by_investor_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_instructions",
                        to="core.company",
                    ),
                ),
                (
                    "subscription_agreement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_instruction",
                        to="core.subscriptionagreement",
                    ),
                ),
            ],
            options={
                "db_table": "payment_instructions",
            },
        ),
        migrations.CreateModel(
            name="InvestmentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("payment_pending", "Payment Pending"),
                            ("payment_received", "Payment Received"),
                            ("shares_issued", "Shares Issued"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_reference", models.CharField(blank=True, max_length=255)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("shares_allocated", models.BigIntegerField(blank=True, null=True)),
                (
                    "price_per_share",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "financing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_transactions",
                        to="core.financing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.subscriptionagreement",
                    ),
                ),
            ],
            options={
                "db_table": "investment_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DRSDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("statement", "DRS Statement"),
                            ("certificate", "Share Certificate"),
                            ("confirmation", "Issuance Confirmation"),
                            ("educational", "DRS Educational Material"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_url", models.URLField(blank=True)),
                (
                    "document_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash for verification",
                        max_length=64,
                    ),
                ),
                ("num_shares", models.BigIntegerField(blank=True, null=True)),
                ("certificate_number", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True, help_text="email, postal, etc", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drs_documents",
                        to="core.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drs_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription_agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drs_documents",
                        to="core.subscriptionagreement",
                    ),
                ),
            ],
            options={
                "db_table": "drs_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccreditedInvestorQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("qualified", "Qualified"),
                            ("not_qualified", "Not Qualified"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "criteria_met",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("income_individual", "Individual Income >$200k"),
                            ("income_combined", "Combined Income >$300k"),
                            ("financial_assets", "Financial Assets ≥$1M"),
                            ("net_assets", "Net Assets ≥$5M"),
                            ("entity_assets", "Entity with Assets ≥$5M"),
                            ("professional", "Registered Dealer/Adviser"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "questionnaire_responses",
                    models.JSONField(
                        default=dict, help_text="Stores all questionnaire answers"
                    ),
                ),
                ("documents_submitted", models.BooleanField(default=False)),
                ("documents_verified", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("qualified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_qualifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accreditation_qualifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accredited_investor_qualifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="accredited__user_id_2e7cee_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="accredited__status_556071_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModuleCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent_seconds", models.IntegerField(default=0)),
                (
                    "quiz_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="core.educationalmodule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "module_completions",
                "indexes": [
                    models.Index(
                        fields=["user", "completed_at"],
                        name="module_comp_user_id_2d8b80_idx",
                    ),
                    models.Index(
                        fields=["module", "-completed_at"],
                        name="module_comp_module__013349_idx",
                    ),
                ],
                "unique_together": {("user", "module")},
            },
        ),
        migrations.AddIndex(
            model_name="subscriptionagreement",
            index=models.Index(
                fields=["investor", "status"], name="subscriptio_investo_87c002_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionagreement",
            index=models.Index(
                fields=["financing", "status"], name="subscriptio_financi_83890f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionagreement",
            index=models.Index(
                fields=["company", "-created_at"], name="subscriptio_company_60b984_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionagreement",
            index=models.Index(
                fields=["status", "-created_at"], name="subscriptio_status_af6584_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionagreement",
            index=models.Index(
                fields=["docusign_envelope_id"], name="subscriptio_docusig_43e4ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmenttransaction",
            index=models.Index(
                fields=["user", "status"], name="investment__user_id_d31481_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmenttransaction",
            index=models.Index(
                fields=["financing", "status"], name="investment__financi_aed774_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmenttransaction",
            index=models.Index(
                fields=["status", "-created_at"], name="investment__status_d37b7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drsdocument",
            index=models.Index(
                fields=["user", "document_type"], name="drs_documen_user_id_ce3379_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drsdocument",
            index=models.Index(
                fields=["subscription_agreement", "-created_at"],
                name="drs_documen_subscri_7d3791_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="drsdocument",
            index=models.Index(
                fields=["delivery_status", "-created_at"],
                name="drs_documen_deliver_692df3_idx",
            ),
        ),
    ]
