# Generated by Django 5.0.1 on 2025-12-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_educationalmodule_financingaggregate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerevent",
            name="stream_url",
            field=models.URLField(
                blank=True, help_text="Live stream embed URL (YouTube, Twitch, etc.)"
            ),
        ),
    ]
