# Generated by Django 5.0.1 on 2025-12-16 11:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_update_user_type_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Brief summary for search results",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Full property description"),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("claim", "Mineral Claim"),
                            ("lease", "Mining Lease"),
                            ("fee_simple", "Fee Simple"),
                            ("option", "Option Agreement"),
                            ("permit", "Exploration Permit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("CA", "Canada"),
                            ("US", "United States"),
                            ("AU", "Australia"),
                            ("MX", "Mexico"),
                            ("PE", "Peru"),
                            ("CL", "Chile"),
                            ("AR", "Argentina"),
                            ("BR", "Brazil"),
                            ("CO", "Colombia"),
                            ("ZA", "South Africa"),
                            ("GH", "Ghana"),
                            ("ML", "Mali"),
                            ("BF", "Burkina Faso"),
                            ("CD", "DRC"),
                            ("ZM", "Zambia"),
                            ("PH", "Philippines"),
                            ("ID", "Indonesia"),
                            ("CN", "China"),
                            ("MN", "Mongolia"),
                            ("OTHER", "Other"),
                        ],
                        max_length=5,
                    ),
                ),
                ("province_state", models.CharField(max_length=100)),
                ("region_district", models.CharField(blank=True, max_length=200)),
                ("nearest_town", models.CharField(blank=True, max_length=200)),
                (
                    "coordinates_lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "coordinates_lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("access_description", models.TextField(blank=True)),
                (
                    "access_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("road", "Road Accessible"),
                            ("fly_in", "Fly-in Only"),
                            ("boat", "Boat Access"),
                            ("combination", "Combination"),
                            ("seasonal", "Seasonal Access"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "claim_numbers",
                    models.JSONField(default=list, help_text="List of claim numbers"),
                ),
                (
                    "total_claims",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "total_hectares",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_acres",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "mineral_rights_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("placer", "Placer"),
                            ("lode", "Lode/Hardrock"),
                            ("both", "Both Placer & Lode"),
                        ],
                        max_length=20,
                    ),
                ),
                ("surface_rights_included", models.BooleanField(default=False)),
                (
                    "claim_status",
                    models.CharField(
                        blank=True,
                        help_text="active, pending renewal, etc",
                        max_length=50,
                    ),
                ),
                ("claim_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "annual_holding_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "primary_mineral",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("copper", "Copper"),
                            ("zinc", "Zinc"),
                            ("lead", "Lead"),
                            ("nickel", "Nickel"),
                            ("cobalt", "Cobalt"),
                            ("lithium", "Lithium"),
                            ("uranium", "Uranium"),
                            ("rare_earth", "Rare Earth Elements"),
                            ("platinum", "Platinum Group"),
                            ("diamonds", "Diamonds"),
                            ("iron", "Iron"),
                            ("molybdenum", "Molybdenum"),
                            ("tungsten", "Tungsten"),
                            ("tin", "Tin"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "secondary_minerals",
                    models.JSONField(
                        blank=True, default=list, help_text="List of secondary minerals"
                    ),
                ),
                (
                    "deposit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vein", "Vein/Lode"),
                            ("placer", "Placer"),
                            ("porphyry", "Porphyry"),
                            ("vms", "VMS (Volcanogenic Massive Sulfide)"),
                            ("sedex", "SEDEX"),
                            ("skarn", "Skarn"),
                            ("epithermal", "Epithermal"),
                            ("orogenic", "Orogenic"),
                            ("iocg", "IOCG"),
                            ("mvt", "MVT"),
                            ("laterite", "Laterite"),
                            ("bif", "BIF (Banded Iron Formation)"),
                            ("carlin", "Carlin-type"),
                            ("intrusion", "Intrusion-related"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("geological_setting", models.TextField(blank=True)),
                ("mineralization_style", models.TextField(blank=True)),
                (
                    "exploration_stage",
                    models.CharField(
                        choices=[
                            ("grassroots", "Grassroots"),
                            ("early", "Early Stage"),
                            ("advanced", "Advanced"),
                            ("development", "Development Ready"),
                            ("past_producer", "Past Producer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "work_completed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of work completed [{type, date, summary}]",
                    ),
                ),
                ("historical_production", models.TextField(blank=True)),
                (
                    "assay_highlights",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Best assay results [{sample_id, mineral, grade, unit}]",
                    ),
                ),
                ("resource_estimate", models.TextField(blank=True)),
                ("has_43_101_report", models.BooleanField(default=False)),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("sale", "Outright Sale"),
                            ("option", "Option to Purchase"),
                            ("joint_venture", "Joint Venture"),
                            ("lease", "Lease"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "asking_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("price_currency", models.CharField(default="CAD", max_length=3)),
                ("price_negotiable", models.BooleanField(default=True)),
                (
                    "minimum_offer",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("option_terms", models.TextField(blank=True)),
                ("joint_venture_terms", models.TextField(blank=True)),
                ("lease_terms", models.TextField(blank=True)),
                (
                    "nsr_royalty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="NSR royalty percentage to retain",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("includes_equipment", models.BooleanField(default=False)),
                ("equipment_description", models.TextField(blank=True)),
                ("additional_terms", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("active", "Active"),
                            ("under_offer", "Under Offer"),
                            ("sold", "Sold"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("featured_until", models.DateTimeField(blank=True, null=True)),
                ("views_count", models.IntegerField(default=0)),
                ("inquiries_count", models.IntegerField(default=0)),
                ("watchlist_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "property_listings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("presentation", "Presentation"),
                            ("spreadsheet", "Spreadsheet"),
                            ("map", "Map"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Image"),
                            ("gallery", "Gallery"),
                            ("logo", "Company Logo"),
                            ("factsheet", "Fact Sheet"),
                            ("investor_presentation", "Investor Presentation"),
                            ("technical_report", "Technical Report (NI 43-101)"),
                            ("financial_report", "Financial Report"),
                            ("annual_report", "Annual Report"),
                            ("news_release", "News Release"),
                            ("map_geological", "Geological Map"),
                            ("map_location", "Location Map"),
                            ("map_claims", "Claims Map"),
                            ("drilling_results", "Drilling Results"),
                            ("assay_certificate", "Assay Certificate"),
                            ("permit", "Permit/License"),
                            ("corporate", "Corporate Document"),
                            ("video_corporate", "Corporate Video"),
                            ("video_site", "Site Video"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file_url", models.URLField(blank=True)),
                (
                    "external_url",
                    models.URLField(blank=True, help_text="External link to resource"),
                ),
                ("thumbnail_url", models.URLField(blank=True)),
                (
                    "file_size_mb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("file_format", models.CharField(blank=True, max_length=20)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary/hero image for the company"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Visible to all users or only subscribers",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured resource shown prominently"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="core.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this resource is specific to this project",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_resources",
                        to="core.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_company_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "company_resources",
                "ordering": ["sort_order", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_price_id", models.CharField(blank=True, max_length=255)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly ($20/month)"),
                            ("annual", "Annual ($200/year)"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trial Period"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete Expired"),
                            ("paused", "Paused"),
                        ],
                        default="trialing",
                        max_length=30,
                    ),
                ),
                (
                    "price_cents",
                    models.IntegerField(
                        default=2000, help_text="Price in cents (2000 = $20)"
                    ),
                ),
                ("trial_start", models.DateTimeField(blank=True, null=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Enabled features for this subscription",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="InvestmentInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_accredited_investor",
                    models.BooleanField(
                        help_text="User confirmed they are an accredited investor"
                    ),
                ),
                ("accreditation_confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shares_requested",
                    models.BigIntegerField(
                        help_text="Number of shares the investor is interested in",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "price_per_share",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price per share at time of interest registration",
                        max_digits=10,
                    ),
                ),
                (
                    "investment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total investment amount (shares * price)",
                        max_digits=15,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("term_sheet_confirmed", models.BooleanField(default=False)),
                (
                    "term_sheet_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "subscription_agreement_confirmed",
                    models.BooleanField(default=False),
                ),
                (
                    "subscription_agreement_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Email for follow-up communications", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for follow-up",
                        max_length=20,
                    ),
                ),
                (
                    "risk_acknowledged",
                    models.BooleanField(
                        default=False, help_text="User acknowledged investment risks"
                    ),
                ),
                ("risk_acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("qualified", "Qualified"),
                            ("contacted", "Contacted"),
                            ("converted", "Converted to Subscription"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_notes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_interests",
                        to="core.company",
                    ),
                ),
                (
                    "financing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_interests",
                        to="core.financing",
                    ),
                ),
                (
                    "subscription_agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interest_registrations",
                        to="core.subscriptionagreement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "investment_interests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentInterestAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_interest_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of investors who expressed interest",
                    ),
                ),
                (
                    "total_shares_requested",
                    models.BigIntegerField(
                        default=0,
                        help_text="Total shares requested across all interests",
                    ),
                ),
                (
                    "total_amount_interested",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total investment amount interested",
                        max_digits=15,
                    ),
                ),
                (
                    "percentage_filled",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of financing goal filled by interests",
                        max_digits=5,
                    ),
                ),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "financing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_aggregate",
                        to="core.financing",
                    ),
                ),
            ],
            options={
                "db_table": "investment_interest_aggregates",
            },
        ),
        migrations.CreateModel(
            name="NewsScrapeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "is_scheduled",
                    models.BooleanField(
                        default=False, help_text="Whether this was a scheduled job"
                    ),
                ),
                ("sources_processed", models.IntegerField(default=0)),
                ("articles_found", models.IntegerField(default=0)),
                ("articles_new", models.IntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered manual scrape, null for scheduled",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "news_scrape_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the source", max_length=200
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Base URL of the news source", unique=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether to include in scraping"
                    ),
                ),
                (
                    "scrape_selector",
                    models.CharField(
                        blank=True,
                        help_text="CSS selector for article links (optional, for advanced configuration)",
                        max_length=500,
                    ),
                ),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
                ("last_scrape_status", models.CharField(blank=True, max_length=50)),
                ("articles_found_last_scrape", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_news_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "news_sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "url",
                    models.URLField(help_text="URL to the full article", unique=True),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Publication date from the source",
                        null=True,
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=200)),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Article excerpt or summary if available"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Featured image URL if available"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags or categories from source",
                    ),
                ),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, help_text="Whether to show in the feed"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="core.newssource",
                    ),
                ),
            ],
            options={
                "db_table": "news_articles",
                "ordering": ["-published_at", "-scraped_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("general", "General Information"),
                            ("site_visit", "Site Visit Request"),
                            ("offer", "Making an Offer"),
                            ("documents", "Document Request"),
                            ("technical", "Technical Questions"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                (
                    "contact_preference",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("either", "Either"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("response", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("is_nda_signed", models.BooleanField(default=False)),
                ("nda_signed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inquirer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="core.propertylisting",
                    ),
                ),
            ],
            options={
                "db_table": "property_inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InquiryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.propertyinquiry",
                    ),
                ),
            ],
            options={
                "db_table": "inquiry_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeaturedPropertyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_manual_selection",
                    models.BooleanField(
                        default=False,
                        help_text="True if manually selected by admin, False for auto-rotation",
                    ),
                ),
                ("selected_at", models.DateTimeField(auto_now=True)),
                (
                    "next_auto_rotation",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the next automatic rotation will occur",
                        null=True,
                    ),
                ),
                (
                    "selected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="featured_property_selections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="featured_config",
                        to="core.propertylisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured Property Configuration",
                "verbose_name_plural": "Featured Property Configuration",
                "db_table": "featured_property_config",
            },
        ),
        migrations.CreateModel(
            name="PropertyMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("map", "Map"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Image"),
                            ("gallery", "Gallery"),
                            ("geological_map", "Geological Map"),
                            ("claim_map", "Claim Map"),
                            ("location_map", "Location Map"),
                            ("assay", "Assay Certificate"),
                            ("report", "Technical Report"),
                            ("permit", "Permit/License"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file_url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True)),
                (
                    "file_size_mb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("file_format", models.CharField(blank=True, max_length=20)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary/hero image for the listing"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="core.propertylisting",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "property_media",
                "ordering": ["sort_order", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyWatchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Personal notes about this listing"
                    ),
                ),
                (
                    "price_alert",
                    models.BooleanField(
                        default=False, help_text="Alert on price changes"
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlisted_by",
                        to="core.propertylisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_watchlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "property_watchlist",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="ProspectorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional company/business name",
                        max_length=200,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "years_experience",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of mineral specializations",
                    ),
                ),
                (
                    "regions_active",
                    models.JSONField(
                        blank=True, default=list, help_text="List of active regions"
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of certifications [{name, issuer, year}]",
                    ),
                ),
                ("website_url", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("profile_image_url", models.URLField(blank=True)),
                ("total_listings", models.IntegerField(default=0)),
                ("active_listings", models.IntegerField(default=0)),
                ("successful_transactions", models.IntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=3
                    ),
                ),
                ("commission_agreement_accepted", models.BooleanField(default=False)),
                (
                    "commission_agreement_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "commission_agreement_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prospector_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prospector_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProspectorCommissionAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=10)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=5
                    ),
                ),
                (
                    "full_legal_name",
                    models.CharField(
                        help_text="Full legal name as signature", max_length=300
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("agreement_text", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "prospector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_agreements",
                        to="core.prospectorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "prospector_commission_agreements",
                "ordering": ["-accepted_at"],
            },
        ),
        migrations.AddField(
            model_name="propertylisting",
            name="prospector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="core.prospectorprofile",
            ),
        ),
        migrations.CreateModel(
            name="SavedPropertySearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "search_criteria",
                    models.JSONField(help_text="Search filter parameters"),
                ),
                ("email_alerts", models.BooleanField(default=True)),
                (
                    "alert_frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_alerted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_property_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_property_searches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpeakingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("conference", "Conference"),
                            ("webinar", "Webinar"),
                            ("investor_day", "Investor Day"),
                            ("roadshow", "Roadshow"),
                            ("agm", "Annual General Meeting"),
                            ("site_visit", "Site Visit"),
                            ("panel", "Panel Discussion"),
                            ("presentation", "Presentation"),
                            ("interview", "Interview"),
                            ("podcast", "Podcast"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "event_name",
                    models.CharField(
                        blank=True,
                        help_text="Conference/event name if applicable",
                        max_length=300,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location or 'Virtual'",
                        max_length=300,
                    ),
                ),
                ("is_virtual", models.BooleanField(default=False)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "timezone",
                    models.CharField(default="America/Toronto", max_length=50),
                ),
                (
                    "registration_url",
                    models.URLField(
                        blank=True, help_text="Link to register for the event"
                    ),
                ),
                (
                    "livestream_url",
                    models.URLField(blank=True, help_text="Link to watch live"),
                ),
                (
                    "recording_url",
                    models.URLField(
                        blank=True, help_text="Link to recording after event"
                    ),
                ),
                (
                    "presentation_url",
                    models.URLField(
                        blank=True, help_text="Link to presentation slides"
                    ),
                ),
                (
                    "speakers",
                    models.TextField(
                        blank=True, help_text="Names and titles of company speakers"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("live", "Live Now"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaking_events",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_speaking_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "speaking_events",
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_invoice_id", models.CharField(max_length=255, unique=True)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                            ("uncollectible", "Uncollectible"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount_cents", models.IntegerField(help_text="Amount in cents")),
                ("currency", models.CharField(default="usd", max_length=3)),
                ("invoice_date", models.DateTimeField()),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("invoice_pdf_url", models.URLField(blank=True)),
                ("hosted_invoice_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="core.companysubscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="CompanyAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ir_manager", "IR Manager"),
                            ("ceo", "CEO"),
                            ("cfo", "CFO"),
                            ("marketing", "Marketing"),
                            ("communications", "Communications"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                (
                    "justification",
                    models.TextField(
                        help_text="Why the user should be granted access to this company"
                    ),
                ),
                (
                    "work_email",
                    models.EmailField(
                        help_text="Work email for verification (should match company domain)",
                        max_length=254,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="core.company",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_access_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_access_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "company_access_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="company_acc_status_a6c609_idx",
                    ),
                    models.Index(
                        fields=["company", "status"],
                        name="company_acc_company_b4dd7c_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="companyaccessrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user", "company"),
                name="unique_pending_request_per_user_company",
            ),
        ),
        migrations.AddIndex(
            model_name="companyresource",
            index=models.Index(
                fields=["company", "resource_type"],
                name="company_res_company_1117f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companyresource",
            index=models.Index(
                fields=["company", "category"], name="company_res_company_32dc4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyresource",
            index=models.Index(
                fields=["company", "is_primary"], name="company_res_company_8d1cf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyresource",
            index=models.Index(
                fields=["project", "category"], name="company_res_project_28cb5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyresource",
            index=models.Index(
                fields=["company", "is_featured"], name="company_res_company_70b9f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companysubscription",
            index=models.Index(
                fields=["stripe_customer_id"], name="company_sub_stripe__a5329b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companysubscription",
            index=models.Index(
                fields=["stripe_subscription_id"], name="company_sub_stripe__1da1d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companysubscription",
            index=models.Index(fields=["status"], name="company_sub_status_c5a59c_idx"),
        ),
        migrations.AddIndex(
            model_name="investmentinterest",
            index=models.Index(
                fields=["user", "financing"], name="investment__user_id_526010_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentinterest",
            index=models.Index(
                fields=["financing", "status"], name="investment__financi_339b8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentinterest",
            index=models.Index(
                fields=["company", "-created_at"], name="investment__company_ad97e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentinterest",
            index=models.Index(
                fields=["status", "-created_at"], name="investment__status_d5d9bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentinterest",
            index=models.Index(
                fields=["is_accredited_investor"], name="investment__is_accr_16d9fb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentinterest",
            constraint=models.UniqueConstraint(
                fields=("user", "financing"), name="unique_user_financing_interest"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["-published_at"], name="news_articl_publish_d1e015_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["source", "-published_at"],
                name="news_articl_source__739a69_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["is_visible", "-published_at"],
                name="news_articl_is_visi_ac293f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inquirymessage",
            index=models.Index(
                fields=["inquiry", "created_at"], name="inquiry_mes_inquiry_2f1784_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inquirymessage",
            index=models.Index(
                fields=["sender", "-created_at"], name="inquiry_mes_sender__1cbfab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyinquiry",
            index=models.Index(
                fields=["listing", "status"], name="property_in_listing_80a52b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyinquiry",
            index=models.Index(
                fields=["inquirer", "-created_at"],
                name="property_in_inquire_0c50bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propertyinquiry",
            index=models.Index(
                fields=["status", "-created_at"], name="property_in_status_e55812_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertymedia",
            index=models.Index(
                fields=["listing", "media_type"], name="property_me_listing_a034d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertymedia",
            index=models.Index(
                fields=["listing", "is_primary"], name="property_me_listing_532bb4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertywatchlist",
            unique_together={("user", "listing")},
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["status", "-created_at"], name="property_li_status_f8708e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["country", "province_state"],
                name="property_li_country_179bfb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["primary_mineral", "status"],
                name="property_li_primary_15369c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["exploration_stage", "status"],
                name="property_li_explora_31974b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["listing_type", "status"], name="property_li_listing_4c3a75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["prospector", "-created_at"],
                name="property_li_prospec_4e9f13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["-views_count"], name="property_li_views_c_321846_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["is_featured", "-created_at"],
                name="property_li_is_feat_c2bc44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="speakingevent",
            index=models.Index(
                fields=["company", "status"], name="speaking_ev_company_a92053_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="speakingevent",
            index=models.Index(
                fields=["company", "-start_datetime"],
                name="speaking_ev_company_5e47e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="speakingevent",
            index=models.Index(
                fields=["status", "-start_datetime"],
                name="speaking_ev_status_a58bfa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="speakingevent",
            index=models.Index(
                fields=["is_featured", "-start_datetime"],
                name="speaking_ev_is_feat_f839ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptioninvoice",
            index=models.Index(
                fields=["stripe_invoice_id"], name="subscriptio_stripe__eb985c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptioninvoice",
            index=models.Index(
                fields=["subscription", "-invoice_date"],
                name="subscriptio_subscri_5c2193_idx",
            ),
        ),
    ]
