# Generated by Django 5.0.1 on 2025-12-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_prospectorprofile_prospectorcommissionagreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Platform Admin'), ('company', 'Company Representative'), ('investor', 'Investor'), ('analyst', 'Analyst'), ('mining_company', 'Mining Company'), ('prospector', 'Prospector'), ('student', 'Student')], default='investor', max_length=20),
        ),
    ]
