# Generated by Django 5.0.1 on 2025-12-17 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_investment_interest"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or class", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Store Categories",
                "db_table": "store_categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StoreShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("min_weight_grams", models.IntegerField(default=0)),
                ("max_weight_grams", models.IntegerField(default=99999999)),
                ("price_cents", models.IntegerField()),
                ("estimated_days_min", models.IntegerField(default=3)),
                ("estimated_days_max", models.IntegerField(default=7)),
                (
                    "countries",
                    models.JSONField(
                        default=list, help_text="List of country codes: ['US', 'CA']"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "store_shipping_rates",
                "ordering": ["display_order", "price_cents"],
            },
        ),
        migrations.CreateModel(
            name="StoreCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="For anonymous/guest carts",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "abandoned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp for cart abandonment tracking",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_carts",
            },
        ),
        migrations.CreateModel(
            name="StoreOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("subtotal_cents", models.IntegerField(default=0)),
                ("shipping_cents", models.IntegerField(default=0)),
                ("tax_cents", models.IntegerField(default=0)),
                ("total_cents", models.IntegerField(default=0)),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "shipping_address",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full shipping address"
                    ),
                ),
                ("shipping_rate_name", models.CharField(blank=True, max_length=100)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(help_text="Supports Markdown for rich formatting"),
                ),
                ("short_description", models.CharField(blank=True, max_length=500)),
                (
                    "price_cents",
                    models.IntegerField(
                        help_text="Price in cents (e.g., 5000 = $50.00)"
                    ),
                ),
                (
                    "compare_at_price_cents",
                    models.IntegerField(
                        blank=True, help_text="Original price for sale items", null=True
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical Product"),
                            ("digital", "Digital Download"),
                        ],
                        default="physical",
                        max_length=20,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "inventory_count",
                    models.IntegerField(default=0, help_text="Available stock"),
                ),
                (
                    "weight_grams",
                    models.IntegerField(
                        default=0, help_text="Weight in grams for shipping calculation"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "badges",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of badge slugs: rare, limited_edition, community_favorite, new_arrival",
                    ),
                ),
                (
                    "provenance_info",
                    models.TextField(
                        blank=True,
                        help_text="History and origin for premium/vault items",
                    ),
                ),
                (
                    "authentication_docs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Certificates, lab reports, expert verification URLs",
                    ),
                ),
                (
                    "min_price_for_inquiry",
                    models.IntegerField(
                        default=500000,
                        help_text="Price threshold above which 'Inquire' button shows instead of Add to Cart",
                    ),
                ),
                ("total_sold", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="core.storecategory",
                    ),
                ),
            ],
            options={
                "db_table": "store_products",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreDigitalAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_url", models.URLField(help_text="S3 URL to the file")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                (
                    "download_limit",
                    models.IntegerField(
                        default=5, help_text="Maximum number of downloads allowed"
                    ),
                ),
                (
                    "expiry_hours",
                    models.IntegerField(
                        default=72, help_text="Hours until download link expires"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_assets",
                        to="core.storeproduct",
                    ),
                ),
            ],
            options={
                "db_table": "store_digital_assets",
            },
        ),
        migrations.CreateModel(
            name="StoreProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(help_text="URL to product image")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("display_order", models.IntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.storeproduct",
                    ),
                ),
            ],
            options={
                "db_table": "store_product_images",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StoreProductInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("negotiating", "Negotiating"),
                            ("sold", "Sold"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(help_text="User's inquiry message")),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone")],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="core.storeproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_product_inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreProductShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shared_to",
                    models.CharField(
                        choices=[
                            ("forum", "Forum Discussion"),
                            ("inquiry", "Property Inquiry"),
                            ("direct_message", "Direct Message"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "destination_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of forum thread, inquiry, or chat room",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="core.storeproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_product_shares",
            },
        ),
        migrations.CreateModel(
            name="StoreProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Large', 'Digital', 'Physical'", max_length=100
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=100)),
                (
                    "price_cents_override",
                    models.IntegerField(
                        blank=True,
                        help_text="Override price for this variant",
                        null=True,
                    ),
                ),
                ("inventory_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="core.storeproduct",
                    ),
                ),
            ],
            options={
                "db_table": "store_product_variants",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StoreOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("variant_name", models.CharField(blank=True, max_length=100)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price_cents", models.IntegerField()),
                ("digital_download_url", models.URLField(blank=True)),
                ("download_count", models.IntegerField(default=0)),
                ("download_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.storeorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="core.storeproduct",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="core.storeproductvariant",
                    ),
                ),
            ],
            options={
                "db_table": "store_order_items",
            },
        ),
        migrations.CreateModel(
            name="StoreCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.storecart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="core.storeproduct",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_items",
                        to="core.storeproductvariant",
                    ),
                ),
            ],
            options={
                "db_table": "store_cart_items",
            },
        ),
        migrations.CreateModel(
            name="StoreRecentPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("is_anonymous", models.BooleanField(default=True)),
                ("amount_cents", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_purchases",
                        to="core.storeorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_purchases",
                        to="core.storeproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recent_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_recent_purchases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStoreBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("founder", "Founder"),
                            ("bronze_collector", "Bronze Collector"),
                            ("silver_prospector", "Silver Prospector"),
                            ("gold_miner", "Gold Miner"),
                        ],
                        max_length=30,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                ("total_spent_cents", models.IntegerField(default=0)),
                ("order_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_store_badges",
            },
        ),
        migrations.AddIndex(
            model_name="storecart",
            index=models.Index(fields=["user"], name="store_carts_user_id_cb1574_idx"),
        ),
        migrations.AddIndex(
            model_name="storecart",
            index=models.Index(
                fields=["session_key"], name="store_carts_session_44af66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeorder",
            index=models.Index(
                fields=["user", "-created_at"], name="store_order_user_id_2f98f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeorder",
            index=models.Index(fields=["status"], name="store_order_status_1814f8_idx"),
        ),
        migrations.AddIndex(
            model_name="storeorder",
            index=models.Index(
                fields=["stripe_checkout_session_id"],
                name="store_order_stripe__c4ec65_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storeproduct",
            index=models.Index(
                fields=["category", "is_active"], name="store_produ_categor_1fb8dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeproduct",
            index=models.Index(
                fields=["product_type", "is_active"],
                name="store_produ_product_a4c1c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storeproduct",
            index=models.Index(fields=["slug"], name="store_produ_slug_981c9b_idx"),
        ),
        migrations.AddIndex(
            model_name="storeproductshare",
            index=models.Index(
                fields=["product", "-created_at"], name="store_produ_product_5e32a7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storecartitem",
            unique_together={("cart", "product", "variant")},
        ),
        migrations.AddIndex(
            model_name="storerecentpurchase",
            index=models.Index(
                fields=["-created_at"], name="store_recen_created_358c9b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userstorebadge",
            unique_together={("user", "badge_type")},
        ),
    ]
