# Generated by Django 5.0.1 on 2025-12-29 16:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_store_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="auto_populated",
            field=models.BooleanField(
                default=False, help_text="Was this company auto-populated via scraping?"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="data_completeness_score",
            field=models.IntegerField(
                default=0,
                help_text="0-100 score indicating data completeness",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="general_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="company",
            name="general_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="company",
            name="last_scraped_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time data was scraped", null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="logo_file",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="company",
            name="media_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="company",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="requires_manual_review",
            field=models.BooleanField(
                default=False, help_text="Flagged for manual review"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="source_website_url",
            field=models.URLField(
                blank=True, help_text="Original website URL used for scraping"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="street_address",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="company",
            name="tagline",
            field=models.CharField(
                blank=True, help_text="Company tagline or slogan", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="CompanyPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("board_director", "Board Director"),
                            ("executive", "Executive"),
                            ("technical_team", "Technical Team"),
                            ("advisor", "Advisor"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Job title, e.g., 'CEO', 'VP Exploration'",
                        max_length=200,
                    ),
                ),
                ("biography", models.TextField(blank=True)),
                ("photo_url", models.URLField(blank=True)),
                (
                    "photo_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_people/"
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="URL where this data was found"
                    ),
                ),
                (
                    "extraction_confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="Confidence score of extraction (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("extracted_at", models.DateTimeField(blank=True, null=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company People",
                "db_table": "company_people",
                "ordering": ["company", "role_type", "display_order", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="FailedCompanyDiscovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=300)),
                ("website_url", models.URLField(blank=True)),
                ("failure_reason", models.TextField()),
                ("attempts", models.IntegerField(default=1)),
                ("last_attempted_at", models.DateTimeField(auto_now=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_discoveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failed_discoveries",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Failed Company Discoveries",
                "db_table": "failed_company_discoveries",
                "ordering": ["-last_attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name_input",
                    models.CharField(
                        help_text="Original company name or URL input", max_length=300
                    ),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, help_text="Target website URL"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "sections_to_process",
                    models.JSONField(
                        default=list, help_text="List of sections to scrape"
                    ),
                ),
                ("sections_completed", models.JSONField(default=list)),
                ("sections_failed", models.JSONField(default=list)),
                (
                    "data_extracted",
                    models.JSONField(
                        default=dict, help_text="Extracted data before saving to models"
                    ),
                ),
                ("documents_found", models.IntegerField(default=0)),
                ("people_found", models.IntegerField(default=0)),
                ("news_found", models.IntegerField(default=0)),
                ("error_messages", models.JSONField(default=list)),
                ("error_traceback", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraping_jobs",
                        to="core.company",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraping_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scraping_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("presentation", "Corporate Presentation"),
                            ("fact_sheet", "Fact Sheet"),
                            ("ni43101", "NI 43-101 Technical Report"),
                            ("financial_report", "Financial Report"),
                            ("annual_report", "Annual Report"),
                            ("quarterly_report", "Quarterly Report"),
                            ("news_release", "News Release"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "source_url",
                    models.URLField(help_text="Original URL where document was found"),
                ),
                (
                    "file_path",
                    models.FileField(
                        blank=True, null=True, upload_to="company_documents/"
                    ),
                ),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "file_format",
                    models.CharField(
                        blank=True, help_text="e.g., pdf, pptx", max_length=20
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                (
                    "is_latest",
                    models.BooleanField(
                        default=True,
                        help_text="Is this the latest version of this document type?",
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True, help_text="Extracted text content for search"
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("extracted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraped_documents",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_documents",
                "ordering": ["-publication_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "document_type"],
                        name="company_doc_company_335e09_idx",
                    ),
                    models.Index(
                        fields=["company", "is_latest"],
                        name="company_doc_company_84eb6e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Full text content of news release"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, help_text="AI-generated summary"),
                ),
                ("source_url", models.URLField(help_text="URL of the news release")),
                (
                    "is_pdf",
                    models.BooleanField(
                        default=False, help_text="Is the source a PDF file?"
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("publication_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "categories",
                    models.JSONField(
                        blank=True, default=list, help_text="Auto-detected categories"
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True, default=list, help_text="Extracted keywords"
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraped_news",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company News",
                "db_table": "company_news",
                "ordering": ["-publication_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "publication_date"],
                        name="company_new_company_dd6515_idx",
                    )
                ],
            },
        ),
    ]
