# Generated by Django 5.0.1 on 2025-12-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_documentprocessingjob_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentprocessingjob",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("ni43101", "NI 43-101 Technical Report"),
                    ("pea", "Preliminary Economic Assessment"),
                    ("news_release", "News Release"),
                    ("financial_statement", "Financial Statement"),
                    ("presentation", "Presentation"),
                    ("fact_sheet", "Fact Sheet"),
                    ("other", "Other"),
                ],
                default="ni43101",
                max_length=30,
            ),
        ),
    ]
