# Generated by Django 5.0.1 on 2025-12-30 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_documentprocessingjob_document_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("news_release", "Company News Release"),
                            ("news_article", "External News Article"),
                            ("company_news", "Scraped Company News"),
                        ],
                        max_length=20,
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("section_title", models.CharField(blank=True, max_length=500)),
                ("text", models.TextField()),
                ("token_count", models.IntegerField()),
                (
                    "chroma_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("source_title", models.CharField(max_length=500)),
                ("source_url", models.URLField(blank=True)),
                ("source_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_chunks",
                        to="core.company",
                    ),
                ),
                (
                    "company_news",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="core.companynews",
                    ),
                ),
                (
                    "news_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="core.newsarticle",
                    ),
                ),
                (
                    "news_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="core.newsrelease",
                    ),
                ),
            ],
            options={
                "db_table": "news_chunks",
                "ordering": ["company", "source_date", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["company", "content_type"],
                        name="news_chunks_company_2d2051_idx",
                    ),
                    models.Index(
                        fields=["source_date"], name="news_chunks_source__6bced8_idx"
                    ),
                ],
            },
        ),
    ]
