# Generated by Django 5.0.1 on 2025-12-31 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_news_chunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                help_text="Approval status for user-submitted companies",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="brief_description",
            field=models.CharField(
                blank=True, help_text="Brief company description", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "1-10 employees"),
                    ("11-50", "11-50 employees"),
                    ("51-200", "51-200 employees"),
                    ("201-500", "201-500 employees"),
                    ("501-1000", "501-1000 employees"),
                    ("1000+", "1000+ employees"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Main contact email for user-submitted companies",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="is_user_submitted",
            field=models.BooleanField(
                default=False, help_text="Was this company submitted by a user?"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="presentation",
            field=models.TextField(
                blank=True, help_text="Company presentation text for user submissions"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Reason for rejection if status is rejected"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the company was reviewed", null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who reviewed this company",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted this company",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MetalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metal",
                    models.CharField(
                        choices=[
                            ("XAU", "Gold"),
                            ("XAG", "Silver"),
                            ("XPT", "Platinum"),
                            ("XPD", "Palladium"),
                        ],
                        max_length=3,
                    ),
                ),
                ("bid_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("ask_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "change_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "change_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("source", models.CharField(default="Kitco", max_length=50)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "metal_prices",
                "ordering": ["-scraped_at", "metal"],
                "indexes": [
                    models.Index(
                        fields=["metal", "-scraped_at"],
                        name="metal_price_metal_80418c_idx",
                    ),
                    models.Index(
                        fields=["-scraped_at"], name="metal_price_scraped_8273eb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("close_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("volume", models.BigIntegerField(default=0)),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "change_percent",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("currency", models.CharField(default="CAD", max_length=3)),
                ("source", models.CharField(default="Alpha Vantage", max_length=50)),
                ("date", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_prices",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "stock_prices",
                "ordering": ["-date", "company__ticker_symbol"],
                "indexes": [
                    models.Index(
                        fields=["company", "-date"],
                        name="stock_price_company_df3300_idx",
                    ),
                    models.Index(fields=["-date"], name="stock_price_date_e35baf_idx"),
                    models.Index(
                        fields=["company", "date"],
                        name="stock_price_company_44f2d9_idx",
                    ),
                ],
                "unique_together": {("company", "date")},
            },
        ),
    ]
