# Generated by Django 5.0.1 on 2025-12-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_company_submission_fields'),
        ('core', '0014_news_chunk'),
    ]

    operations = [
    ]
