# Generated by Django 5.0.1 on 2026-01-02 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_merge_20251231_0926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="brief_description",
            field=models.CharField(
                blank=True, help_text="Brief company description", max_length=2000
            ),
        ),
        migrations.CreateModel(
            name="GlossaryTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(db_index=True, max_length=200, unique=True)),
                ("definition", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("reporting", "Reporting & Standards"),
                            ("geology", "Geology & Resources"),
                            ("finance", "Finance & Investment"),
                            ("regulatory", "Regulatory & Legal"),
                            ("operations", "Mining Operations"),
                            ("general", "General Terms"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "related_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of related links with text and url fields",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for SEO",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="glossary_terms_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Glossary Term",
                "verbose_name_plural": "Glossary Terms",
                "db_table": "glossary_terms",
                "ordering": ["term"],
            },
        ),
    ]
