# Generated by Django 5.0.1 on 2026-01-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_company_brief_description_glossaryterm"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlossaryTermSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(db_index=True, max_length=200)),
                ("definition", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("reporting", "Reporting & Standards"),
                            ("geology", "Geology & Resources"),
                            ("finance", "Finance & Investment"),
                            ("regulatory", "Regulatory & Legal"),
                            ("operations", "Mining Operations"),
                            ("general", "General Terms"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "related_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of related links with text and url fields",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for SEO",
                        max_length=500,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_submission",
                        to="core.glossaryterm",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="glossary_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glossary_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Glossary Term Submission",
                "verbose_name_plural": "Glossary Term Submissions",
                "db_table": "glossary_term_submissions",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-submitted_at"],
                        name="glossary_te_status_6a2d49_idx",
                    ),
                    models.Index(
                        fields=["submitted_by", "-submitted_at"],
                        name="glossary_te_submitt_ab2948_idx",
                    ),
                ],
            },
        ),
    ]
