# Generated by Django 5.0.1 on 2026-01-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_glossarytermsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodityprice",
            name="commodity",
            field=models.CharField(
                choices=[
                    ("gold", "Gold (USD/oz)"),
                    ("silver", "Silver (USD/oz)"),
                    ("copper", "Copper (USD/lb)"),
                    ("lithium", "Lithium Carbonate (USD/tonne)"),
                    ("nickel", "Nickel (USD/lb)"),
                    ("cobalt", "Cobalt (USD/lb)"),
                    ("zinc", "Zinc (USD/lb)"),
                    ("lead", "Lead (USD/lb)"),
                    ("uranium", "Uranium (USD/lb)"),
                    ("rare_earths", "Rare Earth Oxides (USD/kg)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="metalprice",
            name="metal",
            field=models.CharField(
                choices=[
                    ("XAU", "Gold"),
                    ("XAG", "Silver"),
                    ("XPT", "Platinum"),
                    ("XPD", "Palladium"),
                    ("CU", "Copper"),
                    ("NI", "Nickel"),
                    ("LI", "Lithium"),
                    ("CO", "Cobalt"),
                    ("REE", "Rare Earth Elements"),
                    ("U", "Uranium"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="primary_commodity",
            field=models.CharField(
                choices=[
                    ("gold", "Gold"),
                    ("silver", "Silver"),
                    ("copper", "Copper"),
                    ("lithium", "Lithium"),
                    ("nickel", "Nickel"),
                    ("cobalt", "Cobalt"),
                    ("rare_earths", "Rare Earth Elements"),
                    ("zinc", "Zinc"),
                    ("lead", "Lead"),
                    ("platinum", "Platinum Group Metals"),
                    ("uranium", "Uranium"),
                    ("graphite", "Graphite"),
                    ("vanadium", "Vanadium"),
                    ("tungsten", "Tungsten"),
                    ("molybdenum", "Molybdenum"),
                    ("multi_metal", "Multi-Metal"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
