# Generated by Django 5.0.1 on 2026-01-05 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_add_critical_minerals_commodities"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsReleaseFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flagged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "detected_keywords",
                    models.JSONField(
                        default=list,
                        help_text="List of financing keywords that triggered the flag",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed_financing", "Confirmed Financing - Created"),
                            ("reviewed_false_positive", "False Positive - Dismissed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "created_financing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_flag",
                        to="core.financing",
                    ),
                ),
                (
                    "news_release",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financing_flag",
                        to="core.newsrelease",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_news_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "news_release_flags",
                "ordering": ["-flagged_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-flagged_at"],
                        name="news_releas_status_5b03d9_idx",
                    )
                ],
            },
        ),
    ]
