# Generated by Django 5.0.1 on 2026-01-09 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_add_news_release_flag_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="companynews",
            name="best_intercept",
            field=models.CharField(
                blank=True, help_text="Best drill intercept mentioned", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="companynews",
            name="financing_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Financing amount in CAD",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companynews",
            name="financing_price_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Price per unit/share",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companynews",
            name="financing_type",
            field=models.CharField(
                choices=[
                    ("none", "No Financing"),
                    ("private_placement", "Private Placement"),
                    ("bought_deal", "Bought Deal"),
                    ("flow_through", "Flow-Through"),
                    ("rights_offering", "Rights Offering"),
                    ("debt", "Debt Financing"),
                    ("warrant_exercise", "Warrant Exercise"),
                    ("other", "Other Financing"),
                ],
                default="none",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="companynews",
            name="has_drill_results",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="companynews",
            name="is_material",
            field=models.BooleanField(
                default=False,
                help_text="Material news (drill results, resource estimates, financings)",
            ),
        ),
        migrations.AddField(
            model_name="companynews",
            name="is_processed",
            field=models.BooleanField(
                default=False, help_text="Has been processed by document processor"
            ),
        ),
        migrations.AddField(
            model_name="companynews",
            name="news_type",
            field=models.CharField(
                choices=[
                    ("general", "General News"),
                    ("drill_results", "Drill Results"),
                    ("resource_estimate", "Resource Estimate"),
                    ("financing", "Financing"),
                    ("acquisition", "Acquisition/Merger"),
                    ("management", "Management Change"),
                    ("exploration", "Exploration Update"),
                    ("production", "Production Update"),
                    ("regulatory", "Regulatory/Permitting"),
                    ("corporate", "Corporate Update"),
                ],
                default="general",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="companynews",
            name="processing_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news_items",
                to="core.documentprocessingjob",
            ),
        ),
    ]
