# Generated by Django 5.0.1 on 2026-01-13 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_news_classification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedNewsURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='false_positive', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_news_urls', to='core.company')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dismissed_news_urls',
            },
        ),
    ]
