# Generated by Django 5.0.1 on 2026-01-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_closed_financing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dismissednewsurl',
            name='normalized_title',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dismissednewsurl',
            name='normalized_url',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dismissednewsurl',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
