# Generated by Django 5.0.1 on 2026-01-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_normalized_fields_to_dismissed_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdata',
            name='change_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='change_percent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='currency',
            field=models.CharField(default='CAD', max_length=3),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='source',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='source_url',
            field=models.URLField(help_text='URL of the news release', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsrelease',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
