# Generated by Django 5.0.1 on 2026-01-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_normalized_fields_to_dismissed_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='source_url',
            field=models.URLField(help_text='URL of the news release', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsrelease',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
