# Generated by Django 5.0.1 on 2026-01-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_missing_fields_to_marketdata_and_metalprice'),
        ('core', '0036_alter_companynews_source_url_alter_newsrelease_url'),
    ]

    operations = [
    ]
