# Generated by Django 5.0.1 on 2026-01-25 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_merge_20260122_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='primary_commodity',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum Group Metals'), ('palladium', 'Palladium'), ('lithium', 'Lithium'), ('cobalt', 'Cobalt'), ('nickel', 'Nickel'), ('graphite', 'Graphite'), ('manganese', 'Manganese'), ('rare_earths', 'Rare Earth Elements'), ('copper', 'Copper'), ('zinc', 'Zinc'), ('lead', 'Lead'), ('iron_ore', 'Iron Ore'), ('tin', 'Tin'), ('uranium', 'Uranium'), ('vanadium', 'Vanadium'), ('tungsten', 'Tungsten'), ('molybdenum', 'Molybdenum'), ('antimony', 'Antimony'), ('niobium', 'Niobium'), ('tantalum', 'Tantalum'), ('multi_metal', 'Multi-Metal'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete'), ('needs_review', 'Needs Review'), ('error', 'Error')], default='incomplete', max_length=20)),
                ('overall_score', models.IntegerField(default=0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('fixes_applied', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='core.company')),
            ],
            options={
                'verbose_name': 'Company Verification Log',
                'verbose_name_plural': 'Company Verification Logs',
                'db_table': 'company_verification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
