# Generated by Django 5.0.1 on 2026-01-28 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_project_primary_commodity_and_more'),
        ('core', '0038_userai_usage'),
    ]

    operations = [
    ]
