# Generated by Django 5.0.1 on 2026-01-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20260127_2122'),
        ('core', '0041_add_soft_delete_fields'),
    ]

    operations = [
    ]
