# Generated by Django 5.0.1 on 2026-01-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_company_news_url'),
        ('core', '0042_merge_20260128_0746'),
    ]

    operations = [
    ]
