# Generated by Django 5.0.1 on 2026-02-06 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_last_working_news_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete'), ('needs_review', 'Needs Review'), ('error', 'Error')], default='incomplete', max_length=20)),
                ('overall_score', models.IntegerField(default=0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('fixes_applied', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company Verification Log',
                'verbose_name_plural': 'Company Verification Logs',
                'db_table': 'company_verification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='drsdocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drsdocument',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_drs_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drsdocument',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='investmentinterest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentinterest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_investment_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentinterest',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_investment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='paymentinstruction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentinstruction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_payment_instructions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentinstruction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='subscriptionagreement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionagreement',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_subscription_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionagreement',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='drsdocument',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drs_documents', to='core.company'),
        ),
        migrations.AlterField(
            model_name='drsdocument',
            name='subscription_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drs_documents', to='core.subscriptionagreement'),
        ),
        migrations.AlterField(
            model_name='drsdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drs_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financingaggregate',
            name='financing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aggregate_data', to='core.financing'),
        ),
        migrations.AlterField(
            model_name='investmentinterest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_interests', to='core.company'),
        ),
        migrations.AlterField(
            model_name='investmentinterest',
            name='financing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_interests', to='core.financing'),
        ),
        migrations.AlterField(
            model_name='investmentinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentinterestaggregate',
            name='financing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interest_aggregate', to='core.financing'),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='financing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_transactions', to='core.financing'),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='subscription_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.subscriptionagreement'),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentinstruction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_instructions', to='core.company'),
        ),
        migrations.AlterField(
            model_name='paymentinstruction',
            name='subscription_agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_instruction', to='core.subscriptionagreement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_commodity',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum Group Metals'), ('palladium', 'Palladium'), ('lithium', 'Lithium'), ('cobalt', 'Cobalt'), ('nickel', 'Nickel'), ('graphite', 'Graphite'), ('manganese', 'Manganese'), ('rare_earths', 'Rare Earth Elements'), ('copper', 'Copper'), ('zinc', 'Zinc'), ('lead', 'Lead'), ('iron_ore', 'Iron Ore'), ('tin', 'Tin'), ('uranium', 'Uranium'), ('vanadium', 'Vanadium'), ('tungsten', 'Tungsten'), ('molybdenum', 'Molybdenum'), ('antimony', 'Antimony'), ('niobium', 'Niobium'), ('tantalum', 'Tantalum'), ('multi_metal', 'Multi-Metal'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionagreement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_agreements', to='core.company'),
        ),
        migrations.AlterField(
            model_name='subscriptionagreement',
            name='financing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_agreements', to='core.financing'),
        ),
        migrations.AlterField(
            model_name='subscriptionagreement',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='drsdocument',
            index=models.Index(fields=['is_deleted'], name='drs_documen_is_dele_9ea91b_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentinterest',
            index=models.Index(fields=['is_deleted'], name='investment__is_dele_3a15c0_idx'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['is_deleted'], name='investment__is_dele_cff95d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstruction',
            index=models.Index(fields=['is_deleted'], name='payment_ins_is_dele_ea7bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionagreement',
            index=models.Index(fields=['is_deleted'], name='subscriptio_is_dele_c69322_idx'),
        ),
        migrations.AddField(
            model_name='companyverificationlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='core.company'),
        ),
    ]
