# Generated by Django 5.0.1 on 2026-02-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_0042_company_news_url_0042_merge_20260128_0746'),
        ('core', '0045_companyverificationlog_drsdocument_deleted_at_and_more'),
    ]

    operations = [
    ]
