# Generated by Django 5.0.1 on 2026-02-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_companyverificationlog_drsdocument_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='idx_company_is_active'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['approval_status'], name='idx_company_approval_status'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active', 'approval_status'], name='idx_company_active_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='idx_project_is_active'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'is_active'], name='idx_project_company_active'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['is_featured', 'is_active'], name='idx_product_featured'),
        ),
    ]
