# Generated by Django 5.0.1 on 2026-02-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_add_performance_indexes'),
        ('core', '0046_merge_production'),
    ]

    operations = [
    ]
