# Generated by Django 5.0.1 on 2026-02-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge_20260208_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financing',
            name='press_release_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
