# Generated by Django 5.0.1 on 2026-03-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_financing_press_release_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dismissednewsurl',
            name='url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
