# Generated by Django 5.0.1 on 2026-03-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_increase_dismissednewsurl_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['ticker_symbol'], name='idx_company_ticker'),
        ),
        migrations.AddIndex(
            model_name='companynews',
            index=models.Index(fields=['company', '-publication_date'], name='company_new_company_12869c_idx'),
        ),
        migrations.AddIndex(
            model_name='newsrelease',
            index=models.Index(fields=['company', '-release_date'], name='news_releas_company_31613c_idx'),
        ),
    ]
