# Generated by Django 5.0.1 on 2026-05-19 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_add_missing_indexes_and_optimize_queries'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('explorer', 'Explorer (Free)'), ('prospector', 'Prospector'), ('miner', 'Miner')], default='explorer', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trial Period'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired')], default='active', max_length=30)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('plan_interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Annual')], default='month', max_length=10)),
                ('price_cents', models.IntegerField(default=0, help_text='Current price in cents')),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PlatformSubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], max_length=20)),
                ('amount_cents', models.IntegerField(help_text='Amount in cents')),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('invoice_date', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_pdf_url', models.URLField(blank=True, default='')),
                ('hosted_invoice_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.platformsubscription')),
            ],
            options={
                'db_table': 'platform_subscription_invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.AddIndex(
            model_name='platformsubscription',
            index=models.Index(fields=['stripe_customer_id'], name='platform_su_stripe__31cabc_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsubscription',
            index=models.Index(fields=['stripe_subscription_id'], name='platform_su_stripe__d0c531_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsubscription',
            index=models.Index(fields=['tier'], name='platform_su_tier_e74521_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsubscription',
            index=models.Index(fields=['status'], name='platform_su_status_6b64df_idx'),
        ),
    ]
