# Generated by Django 5.0.1 on 2026-05-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_metalprice_unit_and_scraped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_briefing_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
