# Generated by Django 5.0.1 on 2026-05-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_user_last_briefing_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_briefing_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
