# Generated by Django 5.0.1 on 2026-08-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_schema_drift_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsubscription',
            name='expiry_notice_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
