# Generated by Django 5.0.1 on 2026-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_grant_expiry_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='financing',
            name='amount_raised_usd',
            field=models.DecimalField(decimal_places=2, help_text="Amount raised in the financing's native currency (usually CAD), despite the field name.", max_digits=15),
        ),
    ]
