# Generated by Django 5.0.1 on 2026-08-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_widen_document_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
