# Generated by Django 5.0.1 on 2026-08-27 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_document_date_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorQuestionThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=200)),
                ('unread_for_editor', models.PositiveIntegerField(default=0)),
                ('unread_for_user', models.PositiveIntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False, help_text='Editor marked this conversation as handled.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The person asking. The editor side is any staff/superuser.', on_delete=django.db.models.deletion.CASCADE, related_name='editor_question_thread', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'editor_question_threads',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorQuestionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_editor', models.BooleanField(default=False)),
                ('content', models.TextField(max_length=5000)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_question_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.editorquestionthread')),
            ],
            options={
                'db_table': 'editor_question_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='editorquestionthread',
            index=models.Index(fields=['-last_message_at'], name='editor_ques_last_me_942e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='editorquestionthread',
            index=models.Index(fields=['is_resolved', '-last_message_at'], name='editor_ques_is_reso_64cb57_idx'),
        ),
        migrations.AddIndex(
            model_name='editorquestionmessage',
            index=models.Index(fields=['thread', 'created_at'], name='editor_ques_thread__b29728_idx'),
        ),
    ]
