# Generated by Django 5.0.1 on 2026-08-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_ask_the_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscription',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'Monthly (CA$50/month)'), ('annual', 'Annual (CA$500/year)')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='price_cents',
            field=models.IntegerField(default=5000, help_text='Price in cents (5000 = CA$50)'),
        ),
    ]
