# Generated by Django 5.0.1 on 2026-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_company_plan_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='former_names',
            field=models.TextField(blank=True, default='', help_text='Previous names, one per line, most recent first. Appended automatically by save() whenever `name` changes. Plain text rather than a JSON list so it substring-matches the same way `name` does — see Company.name_q().'),
        ),
    ]
