# Generated by Django 5.0.1 on 2026-09-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_company_former_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsreportflag',
            name='candidates',
            field=models.JSONField(blank=True, default=list, help_text='Ranked candidate documents: url, text, score, score_reasons'),
        ),
        migrations.AddField(
            model_name='newsreportflag',
            name='document_category',
            field=models.CharField(blank=True, choices=[('filed', 'Report filed — exists now'), ('results', 'Results announced — report due within 45 days'), ('forward', 'Forward-looking — no report to find'), ('unknown', 'Unclassified')], default='', help_text='What the release title implies about whether a report exists', max_length=20),
        ),
        migrations.AddField(
            model_name='newsreportflag',
            name='expected_filing_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsreportflag',
            name='hunt_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsreportflag',
            name='hunt_status',
            field=models.CharField(choices=[('pending', 'Not yet searched'), ('found', 'Candidates found, awaiting review'), ('auto_queued', 'High-confidence candidate queued for processing'), ('not_found', 'Searched, nothing found yet'), ('exhausted', 'Filing window closed without finding a report'), ('not_expected', 'Release does not imply a filed report')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='newsreportflag',
            name='last_hunt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsreportflag',
            name='next_hunt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='newsreportflag',
            name='project_name',
            field=models.CharField(blank=True, default='', help_text="Project the release refers to, matched against the company's Project rows", max_length=200),
        ),
        migrations.AddIndex(
            model_name='newsreportflag',
            index=models.Index(fields=['status', 'next_hunt_at'], name='nrf_status_next_hunt_idx'),
        ),
    ]
