# Generated by Django 5.0.1 on 2026-09-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_report_hunt_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentprocessingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
