# Generated by Django 5.0.1 on 2026-09-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_job_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentprocessingjob',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
