# Generated by Django 5.0.1 on 2026-09-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_job_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschunk',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
