# Generated by Django 5.0.1 on 2026-09-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_widen_newschunk_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_discovered_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last visit by the weekly document-discovery crawl', null=True),
        ),
    ]
